### ISSUE TITLE
We have two `struct ExtensionValue`

### ISSUE THREAD

**Issue by doug-q** [Quantinuum/hugr#989]
one in `hugr::ops::constant`, one in `hugr::extension`. 

`hugr::extension::ExtensionValue` describes a static value provided by and `Extension`;

`hugr::ops::constant::ExtensionValue` is an opaque `Box<dyn CustomConst>` used in the `Value::Extension` variant.

I propose we rename one, although I don't have a good idea for how.

**Comment by cqc-alec** [comment]
I suggest renaming `hugr::ops::constant::ExtensionValue` ... maybe to something like `ExtensionConst`?

**Comment by cqc-alec** [comment]
Yeah either of those sounds OK to me.
